//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower_Unite_Instrument_Autoplayer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tower_Unite_Instrument_Autoplayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die breaks,
        ///custom_notes,
        ///default_breaks,
        ///export_import,
        ///key_bindings,
        ///main_note_window,
        ///modifiers,
        ///music_pieces,
        ///save_load ähnelt.
        /// </summary>
        internal static string _include {
            get {
                return ResourceManager.GetString("_include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edited version by Exblosis
        ///
        ///original code developed by Matias Jensen.
        ///
        ///This program gives players the ability to play songs in games that supports virtual pianos.
        ///The software is primarily made for Tower Unite and therefore it is not guarantied to work in any other case but it very likely will. ähnelt.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaks allow you to make longer (or shorter) pauses between notes.
        ///Just define a break and use the character in the note creator to use it. ähnelt.
        /// </summary>
        internal static string breaks {
            get {
                return ResourceManager.GetString("breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string custom_notes {
            get {
                return ResourceManager.GetString("custom_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is the Speeds documentation file ähnelt.
        /// </summary>
        internal static string default_breaks {
            get {
                return ResourceManager.GetString("default_breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string export_import {
            get {
                return ResourceManager.GetString("export_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keybindings allow you to define a set of buttons that will let you play and stop the song from within the application on which you use the software.
        ///That way you will not need to tab out between the software and the application. ähnelt.
        /// </summary>
        internal static string key_bindings {
            get {
                return ResourceManager.GetString("key_bindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string main_note_window {
            get {
                return ResourceManager.GetString("main_note_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string modifiers {
            get {
                return ResourceManager.GetString("modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string music_pieces {
            get {
                return ResourceManager.GetString("music_pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string save_load {
            get {
                return ResourceManager.GetString("save_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: 3.0
        ///DELAYS
        ///1
        ///-
        ///300
        ///CUSTOM NOTES
        ///0
        ///SPEEDS
        ///100
        ///70
        ///NOTES
        ///2116
        ///[dip]- - - -[dgp]- - -[hs]-[dgj]- - -  [gjz]-ljHhHgh g f dsh j dsdsh j dsdsh j dsdsg {fgfd} s h j dsdsh j dsdsh j l c xcxzl j h j dsdsh j dsdsh j dsdsg {fgfd} s d sdg dhj hjlcjlc {xcxz} l z-d g h j dsdsh j dsdsh j dsdsg {fgfd} s h j dsdsh j dsdsh j l c xcxzl j h j dsdsh j dsdsh j dsdsg {fgfd} s d sdg dhj hjlcjlc {xcxz} l z-d g hgjlzljhd g h j d  d  s d- -d-d  sd g g h d-d  sd s p s d-d  sd g h j j-h jhg-d-d  dd  ss d g h d  dd s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Senbonzakura {
            get {
                return ResourceManager.GetString("Senbonzakura", resourceCulture);
            }
        }
    }
}
